---
# task/merge_variables file for k3s

- name: "K3S | Merge datastore configuration"
  vars:
    _config_to_merge: "{{ k3s_datastore_configuration }}"
  ansible.builtin.set_fact:
    k3s_configuration: "{{
      k3s_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"

- name: "K3S | Merge networking configuration"
  vars:
    _config_to_merge: "{{ k3s_networking_configuration }}"
  ansible.builtin.set_fact:
    k3s_configuration: "{{
      k3s_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"

- name: "K3S | Merge components configuration"
  vars:
    _config_to_merge: "{{ k3s_components_configuration }}"
  ansible.builtin.set_fact:
    k3s_configuration: "{{
      k3s_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"

- debug:
    msg: "{{ k3s_configuration }}"
