---
# vars file for k3s
k3s_binary_path: /usr/local/bin/k3s
k3s_config_path: "{{ k3s_config_dir }}/k3s.config.yml"
k3s_server_token_file_path: "{{ k3s_config_dir }}/server_token"
k3s_agent_token_file_path: "{{ k3s_config_dir }}/agent_token"
k3s_service_name: k3s

k3s_user: root
k3s_group: root

k3s_github_api: https://api.github.com/repos
k3s_github_project: k3s-io/k3s
k3s_github_url: https://github.com

k3s_deb_architecture_map:
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "arm"
  armv6l: "arm"

k3s_architecture: "{{ k3s_deb_architecture_map[ansible_architecture] | default(ansible_architecture) }}"

k3s_default_join_addr: https://localhost:6443

k3s_needs_to_join: >-
  {{
    (not k3s_server_cluster_init) and
    (k3s_join_addr | default(k3s_default_join_addr)) != k3s_default_join_addr
  }}

k3s_write_kubeconfig_mode: '0644'

k3s_configuration:
  data-dir: "{{ k3s_data_dir }}"

k3s_server_configuration:
  cluster-init: "{{ k3s_server_cluster_init if k3s_server_cluster_init else omit }}"
  server: "{{ k3s_join_addr if k3s_needs_to_join else omit }}"
  secrets-encryption: "{{ k3s_server_enable_secrets_encryption }}"
  token-file: "{{ k3s_server_token_file_path }}"
  agent-token-file: "{{ k3s_agent_token_file_path }}"

k3s_agent_configuration:
  server: "{{ k3s_join_addr }}"
  token-file: "{{ k3s_agent_token_file_path }}"
