---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.k3s_ansible.k3s_labels"
      ansible.builtin.include_role:
        name: "ednz_cloud.k3s_ansible.k3s_labels"
