---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.k3s_ansible.k3s"
      ansible.builtin.include_role:
        name: "ednz_cloud.k3s_ansible.k3s"

    - name: "Install required packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages
      vars:
        manage_apt_packages_list:
          - name: python3-kubernetes
            version: latest
            state: present
          - name: python3-yaml
            version: latest
            state: present
