---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Get node declaration"
      kubernetes.core.k8s_info:
        kubeconfig: "/etc/rancher/k3s/k3s.yaml"
        context: "default"
        api_version: v1
        kind: Node
        name: "{{ ansible_hostname }}"
      register: _node_spec

    - name: "Ensure only 1 node is found"
      ansible.builtin.assert:
        that:
          - _node_spec.resources | length == 1

    - name: "Ensure labels exist"
      ansible.builtin.assert:
        that:
          - _node_spec.resources[0].metadata.labels | length > 2
          - _node_spec.resources[0].metadata.labels["ednz.fr/test"] == "true"
          - _node_spec.resources[0].metadata.labels["ednz.fr/ceph-osd"] == "true"
